### ISSUE TITLE
这个两个import是哪个包里面的？

### ISSUE THREAD

**Issue by beginOfAll** [liguodongiot/llm-action#1]
chatglm/main.py，line number:32 ,34

from trainer_seq2seq import Seq2SeqTrainer
from arguments import ModelArguments, DataTrainingArguments

**Comment by liguodongiot** [comment]
你好,我是李国冬，我已收到你的邮件，我会尽快给您回复。

**Comment by liguodongiot** [comment]
ChatGLM-6B官方提供的哈

- https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/trainer_seq2seq.py
- https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/arguments.py
