### ISSUE TITLE
没有8卡H800类似的配置如何学习本课程. 

### ISSUE THREAD

**Issue by Cheng-lg** [liguodongiot/llm-action#17]
博主您好, 您的教程与资料非常丰富且有代码, 让人感到非常兴奋, 但是我看到您的配置是8卡H800, 这样的配置对于绝大多数的人都无法达到, 请问是否有其他替代方案, 或者colab版本的代码呢, 有很强的学习欲望但是奈何没有硬件作为支撑. 
如果能得到您的回复不胜感激.

**Comment by liguodongiot** [comment]
你好，一张RTX 3090/4090 消费级显卡，可以练习大部分教程哈。比如微调系列、大模型推理等。

**Comment by Cheng-lg** [comment]
感谢回复
