### ISSUE TITLE
请问LLM微调实战中的代码为什么没有了？

### ISSUE THREAD

**Issue by Jennifercai214** [liguodongiot/llm-action#25]
LLM微调实战中所有代码链接点进去显示文件不存在？请问是换位置了吗？
![image](https://github.com/user-attachments/assets/9c692bba-7afa-4dd8-bfbe-ecbf23a8a5c4)
@liguodongiot

**Comment by kongran1** [comment]
到llm-trian里面了

**Comment by Jennifercai214** [comment]
> 到llm-trian里面了

好的谢谢！
