### ISSUE TITLE
微调技术原理综述的文章链接失效

### ISSUE THREAD

**Issue by liukejun1999** [liguodongiot/llm-action#5]
《微调技术原理综述》的文章链接失效了，知乎上找不到对应的文章了
![image](https://github.com/liguodongiot/llm-action/assets/81785191/8a04b730-da06-4d27-8e14-9de0fe8715e5)

**Comment by liguodongiot** [comment]
由于之前发布的这篇文章被知乎误识别为包含AI辅助创作，无法恢复和访问，其实并没有使用AI辅助，无奈妥协，所以重新发布了这篇文章：https://zhuanlan.zhihu.com/p/649755252
