### ISSUE TITLE
并行技术三问题反馈

### ISSUE THREAD

**Issue by liukejun1999** [liguodongiot/llm-action#6]
并行技术三里面这个表述是重复了吗？
![image](https://github.com/liguodongiot/llm-action/assets/81785191/68a220ec-b3c5-4aef-96ac-fd3754c2fe21)

**Comment by liguodongiot** [comment]
@liukejun1999  是的，已修改，文章审核通过了，就可以看到修改内容。

<img width="627" alt="image" src="https://github.com/liguodongiot/llm-action/assets/13220186/133238c7-2aff-4dfb-a03e-3fe8cd11ee3c">
