### ISSUE TITLE
关于分布式并行训练

### ISSUE THREAD

**Issue by Statisticss** [liguodongiot/llm-action#7]
请教一下，我理解目前的Megatron+DeepSpeed是张量并行+数据并行，那有没有张量、数据、流水线三者一起并行的训练框架？

**Comment by liguodongiot** [comment]
@Statisticss  Megatron、Megatron-DeepSpeed、Colossal-AI、PaddlePaddle等AI框架都支持。用得比较多的是Megatron、Megatron-DeepSpeed。
